### ISSUE TITLE
Error message when try to start server:

### ISSUE THREAD

**Issue by shaylevary** [EmulatorJS/EmulatorJS-netplay#29]
Hello my friend,

When i try to start the a netplay server - i get this error message:

[admin@lhnet emuserver]$ npm start

> emuserver@0.15.0 start
> node index.js

body-parser deprecated undefined extended: provide extended option index.js:66:2                                                                  1
The Main Server is now running on port :3000
/home/admin/emuserver/index.js:380
        res.end("error");
        ^

ReferenceError: res is not defined
    at ClientRequest.<anonymous> (/home/admin/emuserver/index.js:380:9)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

I've also noticed that this version doesn't create a directory of files named "node_modules" like on previous version.

I will appreciate your help

**Comment by ethanaobrien** [comment]
Please update the repo. It looks like you are using a (crazily) outdated version. [Line 380](https://github.com/EmulatorJS/EmulatorJS-netplay/blob/49f0481ae81a5637d233017e3a5bba18e3e3d5fb/index.js#L380) doesnt even contain server code

**Comment by shaylevary** [comment]
ok, now i get this error message when try to start:

> emuserver@0.15.0 start
> node index.js

/home/admin/emuserver/node_modules/twilio/lib/rest/Twilio.js:142
    throw new Error('username is required');
    ^

Error: username is required
    at new Twilio (/home/admin/emuserver/node_modules/twilio/lib/rest/Twilio.js:142:11)
    at initializer (/home/admin/emuserver/node_modules/twilio/lib/index.js:10:10)
    at Object.<anonymous> (/home/admin/emuserver/index.js:6:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by shaylevary** [comment]
do you mean to run this command:
git pull

Because when i run it on main root dir i get this error message:
fatal: Not a git repository (or any of the parent directories): .git

I don't have much knowledge on linux code, so maybe i will ask for some help from my sys admin
